### ISSUE TITLE
Recognize search operators in Full Word searches

### ISSUE THREAD

**Issue by navdeepsinghkhalsa** [KhalisFoundation/banidb-api#1]
Add logic to see if +, -, or "" is used in search and don't execute the default "all words" search

**Comment by ManjotS** [comment]
Also should support * like desktop

**Comment by ManjotS** [comment]
see library added for operators for #45 ..

**Comment by rajkambo** [comment]
Alright so reviewing #45 in depth really helped with wrapping my head around how the operators translate to queries, but what are the sample queries we currently accept from the user, and what are the sample queries we are going to expect from the user **after** this change? 

For instance, with #45 the sample queries we currently expect are like: `ang=100`, and some sample queries we expect after the change are something like:
```
ang=100-105
ang<105
ang>100
ang=100+101+105
```

**Comment by ManjotS** [comment]
@tarunsingh5 see  above

**Comment by rajkambo** [comment]
@tarunsingh5 ^^

**Comment by tarunsingh5** [comment]
i dont see the use cases for (-), (<), (>), or (+) wrt to ang

i think (+) is useful when searching multiple full words, (&) and (+) should be the same

**Comment by ManjotS** [comment]
going to add to this.. we can't use & as an operator as its also phapha, a gurmukhi character..

We should also have "-" to exclude things. For example "+sing -praises"

double quote for exact phrase

* for any char 0-N (same as regex .*? or MariaDB %)

**Comment by rajkambo** [comment]
Okay sounds good, so breakdown of what we want so far:

+ this operator is pretty much used as an AND

-  this operator is pretty much used as an EXCLUDE

“” this operator is used for exact phrases

Anything else?

**Comment by ManjotS** [comment]
`*` for any char 0-N (same as regex .*? or MariaDB %)

**Comment by ManjotS** [comment]
merged to dev

**Comment by ManjotS** [comment]
AFAIK this is completed. @rajkambo is there anything outstanding?
