### ISSUE TITLE
punjabi translation wrong

### ISSUE THREAD

**Issue by ManjotS** [KhalisFoundation/BaniDB-API#10]
User report:

"ਗੁਰਮੁਖਿ ਪਿਆਰੇ ਆਇ ਮਿਲੁ ਮੈ ਚਿਰੀ ਵਿਛੁੰਨੇ ਰਾਮ ਰਾਜੇ ॥
ਹੇ ਪਿਆਰੇ ਹਰੀ! ਮੈƒ ਚਿਰ ਦੇ ਵਿਛੁੜੇ ਹੋਏ ƒ ਗੁਰੂ ਦੀ ਰਾਹੀਂ ਆ ਮਿਲ । 
Punjabi translation for this line is incorrectly copied.
Using Safari 10.0.2 on 10.12.2"

**Comment by lalaagolaa** [comment]
This is Triman Singh
 this is missing the 2 nu`s

**Comment by lalaagolaa** [comment]
ƒ = ਨੂੰ

**Comment by tarunsingh5** [comment]
@lalaagolaa can you add to the backend please

**Comment by lalaagolaa** [comment]
done

**Comment by tarunsingh5** [comment]
fixed in prod
