### ISSUE TITLE
Web User Bug Reports

### ISSUE THREAD

**Issue by ManjotS** [KhalisFoundation/banidb-api#101]
Please select which platform you are using:-
Web Version

Feedback Type
Bug Reports

What went wrong?
Antar word missing before aatme...pls check screenshot
 
What should have happened instead?

    
How can the issue be recreated by our team?
pls check screenshot

Which web browser are using?
Chrome 

Operating System
Microsoft Windows

Name
Amanpreet Singh

**Comment by saintsoldierx** [comment]
I already submitted this change in BaniDB CP
