### ISSUE TITLE
Store ik-oang-kaar as 1Eå instead of <> for improved accuracy

### ISSUE THREAD

**Issue by irvanjitsingh** [KhalisFoundation/banidb-api#102]
Would impact character counts and allow the user to select any part of the word

**Comment by tarunsingh5** [comment]
can you explain why there is improved accuracy this way?

**Comment by irvanjitsingh** [comment]
- ikoangkaar is composed of a number, letter and symbol so this would accurately reflect the 3 characters individually combining to form the word
- firstLetter would return ੧ instead of ੧ਓ
- render ੧ and ਓ separately, so for a santhiya app, you could add dashes: 1-Eå, A-lK, etc.
- user can select ੧ and ਓ separately with their cursor which can be more useful

**Comment by ManjotS** [comment]
I don't see the value, but we should add this an option
