### ISSUE TITLE
nanak in translation misleading

### ISSUE THREAD

**Issue by ManjotS** [KhalisFoundation/BaniDB-API#13]
User report

"Bhai Gurdas vaara p 28. Starts with line Poora guru ""nanak"" bin gat nahi.  The translation with ""nanak"" inserted in the line could be confusing. Reference is to Guru Nanak ji (as it Bhai Gurdas ji served the gurus) but more so the emphasis is on ""poora guru"", a FULLY enlightened Being (not 5 per cent, 90 per cent, but 100 per cent enlightened being). Emphasis is on the generic (a fully enlightened being - whoever it may be that has been sanctioned by the LORD ALMIGHTY). This is my humble tiny insight that I would like to share here. This is mentioned many a time in our Sri Guru Granth Sahib. Eg Line 44 Dhoyi tis hee no milay, jin poora guru lebha. He/She who FINDS a FULLY enlightened spiritual being/master finds refuge/shelter. (Because only a poora guru saves redeems, liberates souls: Kal taran guru nanak aiyah (Bhai gurdas ji in that shabad says: that Guru Nanak Ji was sent down by the Lord Almighty to save souls.) In that line, the translation is correct when it is said Guru Nanak ji came down to save souls because that is what Bhai Gurdas ji is saying.
It is just a little subtle but important to reflect on. Thank you so much for your dedication and hard work and making available very good translation for all in this format. I would love to read the translation of Bhai Gurdas ji's vaara - all vaaras - how do i access that via Sikhi to the max. (It was not translated in the old sikhi to the max, so i can't wait to see that in its entirety. Thank u so much . God bless "

**Comment by tarunsingh5** [comment]
@lalaagolaa can you add this in via the BaniDB backend?

**Comment by tarunsingh5** [comment]
closing this for now as it is ambiguous
