### ISSUE TITLE
Web User Bug Reports

### ISSUE THREAD

**Issue by ManjotS** [KhalisFoundation/banidb-api#130]
Please select which platform you are using:-
Web Version

Feedback Type
Bug Reports

What went wrong?
Sat Sri Akaal,
There is a typing error in the English translation on Ang 354. The word ‘not’ is written as ‘net’.
 
What should have happened instead?

    
How can the issue be recreated by our team?
Please correct the spelling mistake.

Which web browser are using?
Safari 

Operating System
Other

Name
Suhani Dhall

**Comment by tarunsingh5** [comment]
submitted change on control panel - will close out when merged - @saintsoldierx can you email the user when i close this ticket?
