### ISSUE TITLE
Search operators doesn't work in prod API

### ISSUE THREAD

**Issue by Gauravjeetsingh** [KhalisFoundation/banidb-api#157]
I am not sure of the root cause. Search operators still give 0 results with the Banidb API. But they work fine in Khajana API.

BaniDB API with 0 search results: https://api.banidb.com/v2/search/hj*r?source=all&page=1
Khajana API with search results: https://api.khajana.org/v2/search/hj*r?source=all&page=1

**Comment by maneetpaul** [comment]
This should be fixed with the latest API release
