### ISSUE TITLE
Multiple English Translation Sources

### ISSUE THREAD

**Issue by maneetpaul** [KhalisFoundation/banidb-api#172]
- [x] - BaniDB (living) 
- [x] - Sant Singh Khalsa 
- [x] - Manmohan Singh
- [ ] - Word for Word (depends on #161)

**Comment by maneetpaul** [comment]
@tarunsingh5 do we have Sant Singh Khalsa or Manmohan Singh original sources available?

**Comment by ManjotS** [comment]
Finished all tasks except #161 . Recommend close in favor of that ticket.
