### ISSUE TITLE
update dev docker image to MariaDB 10.3

### ISSUE THREAD

**Issue by ManjotS** [KhalisFoundation/banidb-api#174]

**Comment by tsingh777** [comment]
Updated banidb-dev image to 10.4.13

**Comment by ManjotS** [comment]
no no bad idea.. 10.4 is significantly different than any proceeding version of mariadb..

It should work.. but don't know if it will for sure.. 10.4,.5,.6 are all generational changes that really should have been major releases.

**Comment by tsingh777** [comment]
Downgraded to 10.3.23
