### ISSUE TITLE
Add Akhand Paath Bhog Ceremony

### ISSUE THREAD

**Issue by maneetpaul** [KhalisFoundation/banidb-api#176]

**Comment by ManjotS** [comment]
Ran

```INSERT INTO `Ceremonies` (`ID`, `Seq`, `Token`, `Gurmukhi`, `GurmukhiUni`, `Transliteration`) VALUES ('5', '5', 'akbhog', 'AKMf pwT swihb Bog', 'ਅਖੰਡ ਪਾਠ ਸਾਹਿਬ ਭੋਗ', 'Akhand Patth Sahib Bhog');

INSERT INTO Ceremonies_Shabad (Seq,Ceremony,ShabadID,VerseID,Updated) select v.id,5,s.ShabadID,v.id,NOW() from Verse v left join Shabad s on s.VerseID=v.ID where PageNo between 1426 and 1431 and sourceID='G' and ID >= 60214;```
