### ISSUE TITLE
Not able to open Shabad Hajare Patshahi 10 from sundar gutka sahib

### ISSUE THREAD

**Issue by ManjotS** [KhalisFoundation/banidb-api#181]
<div> Freshdesk Ticket ID: <a href="https://khalis.freshdesk.com/a/tickets/662">662</a></div>
                       <div> Freshdesk Ticket Agent: Aman Singh</div>
                       <div> Freshdesk Ticket Agent Email: saintsoldierx@gmail.com</div>
                       <div> Ticket Priority: Low</div>
                       <div> Freshdesk Ticket Description: </div><div dir="ltr">
<div>when i clicked on Bani under Sundar Gutka sahib; i am unable to open Shabad Hajare Patshahi 10.</div>
<div>Getting this error:<br>
</div>
<h3 style='margin-bottom: 0.5rem; padding: 0px; font-family: Muli, sans-serif, "Helvetica Neue", Helvetica, Arial, sans-serif; color: rgb(250, 250, 250); line-height: 1.4; font-size: 1.9375rem; background-color: rgb(29, 29, 29)'>ਵਾਹਿਗੁਰੂ! Something isn't working correctly</h3>
<section style='max-width: 40vw; color: rgb(250, 250, 250); font-family: Muli, sans-serif, "Helvetica Neue", Helvetica, Arial, sans-serif; font-size: 18px; background-color: rgb(29, 29, 29)'>This is really unusual. Try <a href="https://www.thewindowsclub.com/clear-cache-cookies-specific-website" target="_blank" rel="noreferrer" style="box-sizing: inherit; background-color: transparent; color: rgb(33, 153, 232); line-height: inherit; cursor: pointer">clearing your cache</a>. If you still face the issue, you may want to hit the Feedback button at the bottom of this page, and report this issue to our team to fix it.</section><div><br></div>
<div>please have a look</div>
<div><br></div>
<div>thank you</div>
<div>Regards</div>
<div>Arshmeet Singh</div>
</div>

**Comment by tarunsingh5** [comment]
@ManjotS @saintsoldierx can we close this out?
