### ISSUE TITLE
Api routes needed for raags and writers

### ISSUE THREAD

**Issue by gurjit03** [KhalisFoundation/banidb-api#196]
With reference to https://github.com/KhalisFoundation/sttm-web/issues/252 here. 
We need API support for raags and writers [ based on baani source ] for the shabads and eventually the baani/shabads to be queried using `baani source` / `writer` / `raag` / `search type` .

**Comment by ManjotS** [comment]
FYI search already allows query string vars of writer, raag, ang range

**Comment by ManjotS** [comment]
https://github.com/KhalisFoundation/banidb-api/blob/dev/api/controllers/shabads.js#L30
