### ISSUE TITLE
Needs way to uniquely identify raag, writer & baani source

### ISSUE THREAD

**Issue by gurjit03** [KhalisFoundation/banidb-api#203]
In reference to this issue https://github.com/KhalisFoundation/sttm-web/issues/252.

When a user is going to change `baani source` in the search tools, we need to update the `writer` and `raag` filters accordingly. Same holds for when user gonna change `raag` and/or `writer` the other respective 2 filters needs to be updated.

So thinking of a solution here possibly an array of objects can make things much easier [ idea ].
```
{
 baaniSourceIdOrName,
 raagId,
 writerId
}
```

**Comment by ManjotS** [comment]
Raag has source now.

Do we need same for writer and bani? Bani (ie rehras etc) can contain more than one source so I don't agree with adding an overall metadata. You should have the metadata already per line.

**Comment by gurjit03** [comment]
@ManjotS veerji, couldn't see anything yet !
![image](https://user-images.githubusercontent.com/8514802/88822931-1e562e80-d1e2-11ea-9279-91597a19674f.png)

**Comment by ManjotS** [comment]
https://api.khajana.org/v2/raags

**Comment by gurjit03** [comment]
@ManjotS veerji, yeah just saw it there are `null` under writers and sourceId is `G` for all the entries
![image](https://user-images.githubusercontent.com/8514802/88826846-d5ed3f80-d1e6-11ea-895c-89e8d6987be2.png)

**Comment by ManjotS** [comment]
Aman is still filling in all of the information. Some of it may remain null
depending on the row.

**Comment by gurjit03** [comment]
@ManjotS okay got it, and sourceId always being `G` is also part of information filling up?

**Comment by ManjotS** [comment]
Yes
