### ISSUE TITLE
Related shabads returning internal server error [on staging]

### ISSUE THREAD

**Issue by gurjit03** [KhalisFoundation/banidb-api#209]
https://stg.sikhitothemax.org/shabad?id=1098
![image](https://user-images.githubusercontent.com/8514802/91601924-1546b180-e988-11ea-8ad4-ce6cd3567f0c.png)

**Comment by saintsoldierx** [comment]
Update on this? @ManjotS

**Comment by tsingh777** [comment]
This error should be fixed now. However, there's no data for related shabads in staging.
