### ISSUE TITLE
pair yaya becomes half yaya in unicode

### ISSUE THREAD

**Issue by ManjotS** [KhalisFoundation/BaniDB-API#24]
https://www.sikhitothemax.org/shabad?id=555335

**Comment by tarunsingh5** [comment]
it's actually becoming a yaksh (devanagri script)

**Comment by tarunsingh5** [comment]
replace with character below
ੵ

Here's a link w/ details:
http://www.unicode.org/L2/L2006/06037r-yakash.pdf

**Comment by tarunsingh5** [comment]
Confirm with if it works with: 

pMcwhruindilAausuMnshijinjGirshwr´au]

on Ang 1408 https://www.sikhitothemax.org/ang?type=5&source=&ang=1408

**Comment by Sarabveer** [comment]
Here is more info:

https://unicode.org/L2/L2016/16294-gurmukhi-chg.pdf

It was partially accepted into Unicode 10, with a statement noting that an alternative version of the Yakash is in use.

**Comment by tarunsingh5** [comment]
confirming that the doc Sarabveer linked to is better to use

**Comment by ManjotS** [comment]
Fix: https://github.com/KhalisFoundation/anvaad-js/pull/27
