### ISSUE TITLE
Search not respecting selected constraints

### ISSUE THREAD

**Issue by savraj** [KhalisFoundation/banidb-api#244]
**Describe the bug**
I'm selecting a few things in search but it's not working -- I'm expecting an AND of the search constraints.

https://www.sikhitothemax.org/search?q=justice&type=3&source=all&writer=12

Search input query GET parameters:
(q) input string: "justice"
(type) full word translation (English)
(source) all
(writer) 12 -- Bhagat Kabeer

**To Reproduce**
1. Go to https://www.sikhitothemax.org/search?q=justice&type=3&source=all&writer=12
2. See that results contain writers that are not Bhagat Kabeer Ji

**Expected behavior**
Results are restricted to writings by Bhagat Kabeer Ji.

**Screenshots**
![image](https://user-images.githubusercontent.com/387613/120078760-a9a88680-c076-11eb-8012-f7d8541c34eb.png)

**Desktop (please complete the following information):**
 - OS: Mac OS 11.4
 - Browser: Brave 1.25.68 (Chromium 91)

**Comment by saintsoldierx** [comment]
This has been fixed @savraj
