### ISSUE TITLE
V2

### ISSUE THREAD

**Issue by navdeepsinghkhalsa** [KhalisFoundation/banidb-api#30]
- [ ] Documentation
- [x] Convert to Node.js
  - [x] Shabads
    - [x] Search
    - [x] Shabad
    - [x] Ang
    - [x] Hukamnama
      - [x] Today
      - [x] Date
    - [x] Random
  - [x] Banis
    - [x] Index
    - [x] Bani
    - [x] Length query (required)
  - [x] Rehats
    - [x] All
    - [x] Chapter list
    - [x] Chapter
    - [x] Search
- [x] Collect Hukamnama archive
- [x] Decide on endpoint names
- [ ] Errors
  - [ ] Codes
  - [ ] Messages
- [x] Decide field name casing
- [ ] Caching directives
- [ ] Output formats (via Accepts header)
  - [x] JSON
  - [ ] XML
  - [ ] YAML

**Comment by ManjotS** [comment]
Few things  to ensure  work:

- [ ] Multi-shabad (ie /shabad/123+334+56544)
- [ ] Multi-search (ie first letters qTb  AND english "longing")
- [ ] Bani Lengths
- [ ] Multi-ang?  (/ang/5+25)
- [ ] All  current and future search methods? Currently we are missing mainletter, spanish, punjabi  trans. maybe  translation='punjabi|english|spanish|etc' &&  searchstring = xyz

Also, do we have  the ability to  pull diffs  for banis, angs,  shabads, all for apps?

**Comment by navdeepsinghkhalsa** [comment]
Could you please create new issues for each of the multiple ones (Shabad, search, Ang)? I feel that they're out of scope. We'll need to update the `banidb` module to support the different types of search at the same time. I'll look into that to get an idea of scope.

 I will add Bani lengths and diffs

**Comment by ManjotS** [comment]
ok, the multi  one would still need to go  into  v2, but can be  after
initial  release
