### ISSUE TITLE
Implement I'm feeling lucky feature in the API

### ISSUE THREAD

**Issue by bogas04** [KhalisFoundation/banidb-api#31]
> I'm absolutely in love with I'm feeling lucky + highlighting. It's like the line comes from mind to screen directly.

It'll be great if API can handle this use case to reduce roundtrip cost.

**Comment by ManjotS** [comment]
@bogas04 do you envision this to do a redirect from /search to /shabad automatically? that seems difficult and also bad for an api. if you can provide a design, I can implement it.

You can achieve a similar effect with ?results=1
