### ISSUE TITLE
this should show next/prev

### ISSUE THREAD

**Issue by ManjotS** [KhalisFoundation/banidb-api#38]
https://www.sikhitothemax.org/shabad?id=31070

**Comment by tarunsingh5** [comment]
it does show next/previous - can we close?

**Comment by ManjotS** [comment]
its a bug,  previous is grayed out.

**Comment by pdvsingh** [comment]
It's a valid bug but is it BaniDB issue or STTM-Web?

**Comment by ManjotS** [comment]
its api
