### ISSUE TITLE
Map SikhNet shabadid to BaniDB ids

### ISSUE THREAD

**Issue by bogas04** [KhalisFoundation/banidb-api#47]
Moving it here https://github.com/KhalisFoundation/sttm-web/issues/452

**Comment by ManjotS** [comment]
This has not been done.

**Comment by tarunsingh5** [comment]
@ManjotS can we use igurbani mappings here?

**Comment by ManjotS** [comment]
We  would have to back map each to their respective shabadids, but
 possibly.

**Comment by pdvsingh** [comment]
Why can't we ask Sikhnet to update their shabad IDs?

**Comment by ManjotS** [comment]
The point is there are countless legacy links we have broken. The longer we
don't fix this the more it doesn't matter. This really should have been
done 2 years ago.

We lose a lot of users that may come from other places due to this.

**Comment by tarunsingh5** [comment]
i'm w/ @pdvsingh on this - let's close this ticket - it's not that critical for us to map to them - they should map to us. We will bring it up w/ Gurmustak at IM

**Comment by ManjotS** [comment]
Thats fine but as I pointed out .. this isn't only sikhnet.. sikhnet is
just an example in the title.. theres random blogs, sites, posts, groups
etc with shabad links expecting old ones
