### ISSUE TITLE
Strip Bani Headers from Related Shabads

### ISSUE THREAD

**Issue by tarunsingh5** [KhalisFoundation/banidb-api#67]
Some Bani Headers still showing 
<img width="991" alt="screen shot 2019-01-29 at 8 53 04 pm" src="https://user-images.githubusercontent.com/35271830/52004489-0fbb7980-247c-11e9-8322-938a6811d64b.png">
<img width="974" alt="screen shot 2019-01-29 at 8 52 28 pm" src="https://user-images.githubusercontent.com/35271830/52004529-2366e000-247c-11e9-8b45-d770b7dd9816.png">

**Comment by tarunsingh5** [comment]
ping @ManjotS

**Comment by tarunsingh5** [comment]
![image](https://user-images.githubusercontent.com/35271830/56462083-a27bfe00-6371-11e9-8fe0-68357c9d87fc.png)

**Comment by ManjotS** [comment]
fixed all cases in this ticket
