### ISSUE TITLE
Error doing SSO using FB

### ISSUE THREAD

**Issue by plug-n-play** [KhalisFoundation/banidb-api#71]
![image](https://user-images.githubusercontent.com/6245927/58028585-af3e6e00-7b38-11e9-80e0-d84c395b143f.png)

On clicking FB icon at https://login.khalis.net/ we get above issue:
![image](https://user-images.githubusercontent.com/6245927/58028696-eb71ce80-7b38-11e9-80d6-dd05aba765dd.png)
 

![image](https://user-images.githubusercontent.com/6245927/58028716-f3317300-7b38-11e9-965e-9041f85f5412.png)

**Comment by pdvsingh** [comment]
Closing this as we are working on a new SSO implementation
