### ISSUE TITLE
Issue with Spanish translation.

### ISSUE THREAD

**Issue by Gauravjeetsingh** [KhalisFoundation/banidb-api#75]
**Describe the bug**
Current spanish translation:

```
ਹਰਿ ਜੂ ਰਾਖਿ ਲੇਹੁ ਪਤਿ ਮੇਰੀ is 
O Dear Lord, please, save my honor!
Oh Dios, salva mi Honor; me aterroriza la muerte en mi corazón.

ਜਮ ਕੋ ਤ੍ਰਾਸ ਭਇਓ ਉਰ ਅੰਤਰਿ ਸਰਨਿ ਗਹੀ ਕਿਰਪਾ ਨਿਧਿ ਤੇਰੀ ॥੧॥ ਰਹਾਉ ॥
The fear of death has entered my heart; I cling to the Protection of Your Sanctuary, O Lord, ocean of mercy. ||1||Pause||
Oh Ser Compasivo, he buscado Tu Refugio. (1‑Pausa)
```

**To Reproduce**
1. Go to 'Search for hjrlp' in mode 'First letter anywhere'
2. Click on 'Display' button and enable the Spanish translation
4. See this incorrection at second and third line of shabad.

**Expected behavior**
The Correct translation would be:
```
ਹਰਿ ਜੂ ਰਾਖਿ ਲੇਹੁ ਪਤਿ ਮੇਰੀ is 
O Dear Lord, please, save my honor!
Oh Dios, salva mi Honor;

ਜਮ ਕੋ ਤ੍ਰਾਸ ਭਇਓ ਉਰ ਅੰਤਰਿ ਸਰਨਿ ਗਹੀ ਕਿਰਪਾ ਨਿਧਿ ਤੇਰੀ ॥੧॥ ਰਹਾਉ ॥
The fear of death has entered my heart; I cling to the Protection of Your Sanctuary, O Lord, ocean of mercy. ||1||Pause||
me aterroriza la muerte en mi corazón; Oh Ser Compasivo, he buscado Tu Refugio. (1‑Pausa)
```

Source for correct translation based on google translate and Inderpreet veerji!

**Desktop:**
 - OS: Ubuntu 16.04
 - Browser : Chrome

**Comment by pdvsingh** [comment]
I think we should close this as this probably needs us to re-look at the DB wide translations.

**Comment by ManjotS** [comment]
submitted to control panel
