### ISSUE TITLE
ASCII char order/precedence issues should be fixed in the data itself where possible

### ISSUE THREAD

**Issue by irvanjitsingh** [KhalisFoundation/banidb-api#94]
s`uD ispwh durMq dubwh su swj snwh durjwn dlYNgy ]

converts to
ਸੱੁਧ ਸਿਪਾਹ ਦੁਰੰਤ ਦੁਬਾਹ ਸੁ ਸਾਜ ਸਨਾਹ ਦੁਰਜਾਨ ਦਲੈਂਗੇ ॥
सु्ुध सिपाह दुरंत दुबाह सु साज सनाह दुरजान दलैंगे ॥

expected
ਸੁੱਧ ਸਿਪਾਹ ਦੁਰੰਤ ਦੁਬਾਹ ਸੁ ਸਾਜ ਸਨਾਹ ਦੁਰਜਾਨ ਦਲੈਂਗੇ ॥
सुद्ध सिपाह दुरंत दुबाह सु साज सनाह दुरजान दलैंगे ॥

Note the incorrect devnagri. In this case, instances of "`u" should be replaced by "u`" instead of handling the edge cases in the respective converter.

**Comment by ManjotS** [comment]
closing in favor of #105
